version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  labels:
    - dependencies
    - dependabot
  open-pull-requests-limit: 5
  commit-message:
    prefix: "deps"
